### ISSUE TITLE
Commit規範說明不齊全

### ISSUE THREAD

**Issue by bloodnighttw** [cheung4843/LMcpsBook#2]
如題
說明模糊
不夠詳細

**Comment by bloodnighttw** [comment]
這邊建議
修改成這樣

第一行為
- ``add: file name 1, file name 2,......etc``
- ``modified: file name 1, file name 2 ,...... etc``
- ``delete: file name 1 , file name 2,...... etc``

第二行為說明修改的詳細內容

For example:
```git
modified: 我好帥.md
我好帥的內容
我好帥我好帥
```

**Comment by cheung4843** [comment]
增加上去了。

**Comment by bloodnighttw** [comment]
解法挺暴力的

Fix in b35a088

**Comment by bloodnighttw** [comment]
fix in b35a088
