### ISSUE TITLE
查看原始碼與修改原始碼的連結無效

### ISSUE THREAD

**Issue by bloodnighttw** [cheung4843/LMcpsBook#3]
![截圖 2024-01-28 15 31 22](https://github.com/cheung4843/LMcpsBook/assets/44264182/e1e69392-b206-4a13-8774-b6f3cdb25366)
會連結至[這個404畫面](https://github.com/cheung4843/LMcpsBook/raw/master/docs/index.md)
然後測試後 發現修改原始碼的連結也是

**Comment by cheung4843** [comment]
參見 `mkdocs.ymal`，註解掉的部分就是這兩個功能，需要參考 https://github.com/squidfunk/mkdocs-material/discussions/4055 來設定。
<img width="174" alt="image" src="https://github.com/cheung4843/LMcpsBook/assets/46809977/a9914664-c187-4462-97bf-400d055b8d01">

**Comment by bloodnighttw** [comment]
解法挺暴力的

**Comment by bloodnighttw** [comment]
fix in b35a088

**Comment by cheung4843** [comment]
available in https://github.com/cheung4843/LMcpsBook/commit/b82820972e71ebe3ebfb76097dd313717dcaf59d

**Comment by bloodnighttw** [comment]
看起來運作的還錯

**Comment by cheung4843** [comment]
還錯?是指哪裡有問題嗎?

**Comment by bloodnighttw** [comment]
沒錯 打錯自
